services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: support_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - support_network